version: "3"
services:
  mysql:
    image: mysql
    container_name: db_mysql
    restart: always
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      # MYSQL_USER: root
      # MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
volumes:
  mysql-data:
